language: objective-c
osx_image: xcode8
podfile: Example/Podfile

notifications:
  webhooks: https://outlook.office365.com/webhook/cdda2aa3-6ecb-4b3c-be58-37c3ecf51f82@e3cf3c98-a978-465f-8254-9d541eeea73c/TravisCI/7937bbbcb04f482db82d650268b0df85/5659d4fa-3061-4ad6-8f54-5cf55bc655de

before_install:
- rvm get head
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod --version
- pod install --project-directory=Example
script:
- set -o pipefail
#- grep SWIFT_VERSION Example/SubscriptionMonitor.xcodeproj/project.pbxproj
- xcodebuild test -workspace Example/Seam3.xcworkspace -scheme Seam3-Example -sdk iphonesimulator -destination "OS=10.0,name=iPhone 7" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
